_target_: src.policy.PendulumEnergyBasedFrictionAdaptive

gain: 0.03
action_min: -0.1
action_max: 0.1
friction_coeff_est_init: 0
sampling_time: $ common.sampling_time
gain_adaptive: 0.003
pd_coeffs: = [0.6, 0.2]
switch_loc: = np.cos(np.pi / 10)
system: ~ system